// Defines an RPC service to simulate a Blockchain implementation

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: threatintel.proto

package threatintel

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThreatIntel_RequestThreatIntel_FullMethodName = "/threatintel.ThreatIntel/RequestThreatIntel"
)

// ThreatIntelClient is the client API for ThreatIntel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The ThreatIntel service definition
type ThreatIntelClient interface {
	// A RPC that simulates reading data from a Blockchain
	RequestThreatIntel(ctx context.Context, in *KeyId, opts ...grpc.CallOption) (*Indicators, error)
}

type threatIntelClient struct {
	cc grpc.ClientConnInterface
}

func NewThreatIntelClient(cc grpc.ClientConnInterface) ThreatIntelClient {
	return &threatIntelClient{cc}
}

func (c *threatIntelClient) RequestThreatIntel(ctx context.Context, in *KeyId, opts ...grpc.CallOption) (*Indicators, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Indicators)
	err := c.cc.Invoke(ctx, ThreatIntel_RequestThreatIntel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThreatIntelServer is the server API for ThreatIntel service.
// All implementations must embed UnimplementedThreatIntelServer
// for forward compatibility.
//
// The ThreatIntel service definition
type ThreatIntelServer interface {
	// A RPC that simulates reading data from a Blockchain
	RequestThreatIntel(context.Context, *KeyId) (*Indicators, error)
	mustEmbedUnimplementedThreatIntelServer()
}

// UnimplementedThreatIntelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThreatIntelServer struct{}

func (UnimplementedThreatIntelServer) RequestThreatIntel(context.Context, *KeyId) (*Indicators, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestThreatIntel not implemented")
}
func (UnimplementedThreatIntelServer) mustEmbedUnimplementedThreatIntelServer() {}
func (UnimplementedThreatIntelServer) testEmbeddedByValue()                     {}

// UnsafeThreatIntelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThreatIntelServer will
// result in compilation errors.
type UnsafeThreatIntelServer interface {
	mustEmbedUnimplementedThreatIntelServer()
}

func RegisterThreatIntelServer(s grpc.ServiceRegistrar, srv ThreatIntelServer) {
	// If the following call pancis, it indicates UnimplementedThreatIntelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThreatIntel_ServiceDesc, srv)
}

func _ThreatIntel_RequestThreatIntel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThreatIntelServer).RequestThreatIntel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThreatIntel_RequestThreatIntel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThreatIntelServer).RequestThreatIntel(ctx, req.(*KeyId))
	}
	return interceptor(ctx, in, info, handler)
}

// ThreatIntel_ServiceDesc is the grpc.ServiceDesc for ThreatIntel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThreatIntel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "threatintel.ThreatIntel",
	HandlerType: (*ThreatIntelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestThreatIntel",
			Handler:    _ThreatIntel_RequestThreatIntel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "threatintel.proto",
}
