// Defines an RPC service to simulate a Blockchain implementation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: threatintel.proto

package threatintel

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyId) Reset() {
	*x = KeyId{}
	mi := &file_threatintel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyId) ProtoMessage() {}

func (x *KeyId) ProtoReflect() protoreflect.Message {
	mi := &file_threatintel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyId.ProtoReflect.Descriptor instead.
func (*KeyId) Descriptor() ([]byte, []int) {
	return file_threatintel_proto_rawDescGZIP(), []int{0}
}

func (x *KeyId) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Indicators struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []byte                 `protobuf:"bytes,1,opt,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Indicators) Reset() {
	*x = Indicators{}
	mi := &file_threatintel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Indicators) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Indicators) ProtoMessage() {}

func (x *Indicators) ProtoReflect() protoreflect.Message {
	mi := &file_threatintel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Indicators.ProtoReflect.Descriptor instead.
func (*Indicators) Descriptor() ([]byte, []int) {
	return file_threatintel_proto_rawDescGZIP(), []int{1}
}

func (x *Indicators) GetAddresses() []byte {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_threatintel_proto protoreflect.FileDescriptor

const file_threatintel_proto_rawDesc = "" +
	"\n" +
	"\x11threatintel.proto\x12\vthreatintel\"\x17\n" +
	"\x05KeyId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"*\n" +
	"\n" +
	"Indicators\x12\x1c\n" +
	"\taddresses\x18\x01 \x01(\fR\taddresses2R\n" +
	"\vThreatIntel\x12C\n" +
	"\x12RequestThreatIntel\x12\x12.threatintel.KeyId\x1a\x17.threatintel.Indicators\"\x00B%Z#github.com/mboom/MedCTI/threatintelb\x06proto3"

var (
	file_threatintel_proto_rawDescOnce sync.Once
	file_threatintel_proto_rawDescData []byte
)

func file_threatintel_proto_rawDescGZIP() []byte {
	file_threatintel_proto_rawDescOnce.Do(func() {
		file_threatintel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_threatintel_proto_rawDesc), len(file_threatintel_proto_rawDesc)))
	})
	return file_threatintel_proto_rawDescData
}

var file_threatintel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_threatintel_proto_goTypes = []any{
	(*KeyId)(nil),      // 0: threatintel.KeyId
	(*Indicators)(nil), // 1: threatintel.Indicators
}
var file_threatintel_proto_depIdxs = []int32{
	0, // 0: threatintel.ThreatIntel.RequestThreatIntel:input_type -> threatintel.KeyId
	1, // 1: threatintel.ThreatIntel.RequestThreatIntel:output_type -> threatintel.Indicators
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_threatintel_proto_init() }
func file_threatintel_proto_init() {
	if File_threatintel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_threatintel_proto_rawDesc), len(file_threatintel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_threatintel_proto_goTypes,
		DependencyIndexes: file_threatintel_proto_depIdxs,
		MessageInfos:      file_threatintel_proto_msgTypes,
	}.Build()
	File_threatintel_proto = out.File
	file_threatintel_proto_goTypes = nil
	file_threatintel_proto_depIdxs = nil
}
